
---

## 🔧 `e_hrms/render.yaml`

```yaml
services:
  - type: web
    name: ehrms-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        value: your_postgres_url
      - key: SECRET_KEY
        value: your_jwt_secret
